# Generated by Django 5.0.6 on 2024-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='checked_in_at',
            new_name='attendance_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='qr_code',
            new_name='qr_code_enter',
        ),
    ]
