# Generated by Django 5.0.6 on 2024-05-20 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_time', models.CharField(max_length=100)),
                ('club_introduction', models.TextField()),
                ('club_details', models.TextField()),
                ('club_contact', models.CharField(max_length=100)),
                ('club_open', models.BooleanField(default=True)),
                ('club_open_start', models.DateField(default=django.utils.timezone.now)),
                ('club_open_end', models.DateField()),
                ('club_pic', models.ImageField(blank=True, null=True, upload_to='club_pics/')),
                ('club_code', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
