# Generated by Django 5.0.6 on 2024-05-19 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_time', models.CharField(max_length=100)),
                ('club_introduction', models.TextField()),
                ('club_details', models.TextField()),
                ('club_contact', models.CharField(max_length=100)),
                ('club_open', models.BooleanField(default=True)),
                ('club_open_start', models.DateField(default=django.utils.timezone.now)),
                ('club_open_end', models.DateField()),
            ],
        ),
    ]
