# Generated by Django 5.0.6 on 2024-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0002_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
